#Common setup
- hosts: tag_Node_Master
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for master"
      private: no
  roles:
  - role: "k8s_common"

- hosts: tag_Node_Slave
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for slave"
      private: no
  roles:
  - role: "k8s_common"

#Master configuration
- hosts: tag_Node_Master
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for master"
      private: no
  roles:
  - role: "k8s_master"

#Slave configuration
- hosts: tag_Node_Slave
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for slave"
      private: no
  roles:
  - role: "k8s_slave"

#Launching wordpress and mysql pods
- hosts: tag_Node_Master
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for master"
      private: no
  vars:
    - ansible_user: ec2-user
    - ansible_ssh_private_key_file: "{{ SSH_KEY_PATH }}"
    - ansible_become: true
  tasks:
    - name: "Checking nodes"
      command: "kubectl get nodes"
      register: nodes
    - debug:
        msg: "{{ nodes.stdout_lines }}"

    - name: "Copying yml files for wordpress and mysql"
      copy:
        dest: / 
        src: "{{ item }}"
      with_items:
        - mysql_secret.yml
        - wp_mysql.yml
        - wordpress.yml  

    - name: "Creating secret named  mysecret" 
      command: "kubectl apply -f /mysql_secret.yml"

    - name: "Creating mysql deployment and service" 
      command: "kubectl apply -f /wp_mysql.yml"

    - name: "Creating wordpress deployment and service" 
      command: "kubectl apply -f /wordpress.yml"
 
    - name: "Printing services"
      command: "kubectl get svc"
      register: svc
   
    - debug:
        msg: "{{ svc }}"
       


