apiVersion: v1
kind: Service
metadata:
  name: "wordpress-svc"
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "wordpress-deploy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: "wordpress"
      labels:
        app: wordpress
    spec:
      containers:
      - name: "wordpress"
        image: "wordpress:5.1.1-php7.3-apache" 
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-mysql-service
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_pass
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: database 
        ports:
          - containerPort: 80
  
