apiVersion: v1
kind: Service
metadata:
  name: wp-mysql-service
spec:
  type: NodePort
  selector:
    app: mysql-wp
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-wp
  template:
    metadata:
      name: "mysql-wp"
      labels:
        app: mysql-wp
    spec:
      containers:
      - name: "mysql-wp"
        image: "mysql:5.7"
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: root_pass
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql_pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: database
        ports:
        - containerPort: 3306
          
        