---
# tasks file for k8s_master

- name: "Pulling Images"
  command: "kubeadm config images pull"


- name: "kubeadm init"
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"


- name: "Creating directory for kube"
  file:
    path: /root/.kube
    state: directory

 
- name: "Changing owner" 
  shell: "cp -i /etc/kubernetes/admin.conf /root/.kube/config && chown $(id-u):$(id-g) /root/.kube/config"


- name: "Flannel setup"
  command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

   
- name: "Generating token for slave"
  command: "kubeadm token create --print-join-command"
  register: master_token
     

- name: "Setting fact for token"
  set_fact:
    token_cmd: "{{ master_token }}"

